language: python
python:
  - "2.6"
  - "2.7"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: NO_COVERAGE="1"
services:
  - redis-server
install:
  - "pip install -r requirements.pip"
  - "pip install coverage"
  - "pip install overalls"
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=vumi_wikipedia"; else COVERAGE_CMD=""; fi
  - VUMITEST_REDIS_DB=1 $COVERAGE_CMD `which trial` vumi_wikipedia
after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
